version: '3'
services:
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=example_pw
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=airflow
        expose:
            - 5432
        volumes:
            - 'db_data:/var/lib/postgresql/data'

    redis:
        image: redis:6.0
        container_name: redis
        restart: always
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        expose:
            - 6379

    flower:
        build: .
        container_name: flower
        image: henryturner27/airflow
        user: airflow
        restart: always
        environment:
            - EXECUTOR=CeleryExecutor
        depends_on:
            - postgres
            - redis
        ports:
            - 5555:5555
        command: sh -c "sleep 5 && airflow celery flower"

    webserver:
        build: .
        container_name: webserver
        image: henryturner27/airflow
        user: airflow
        restart: always
        environment:
            - EXECUTOR=CeleryExecutor
        depends_on:
            - postgres
            - redis
        ports:
            - 8080:8080
        volumes:
          - ./dags:/airflow/dags
        command: sh -c "sleep 5 && airflow db init && airflow users create --role Admin --username admin --email admin@dairflow.com --firstname admin --lastname admin --password admin && airflow webserver"

    scheduler:
        build: .
        container_name: scheduler
        image: henryturner27/airflow
        user: airflow
        restart: always
        environment:
            - EXECUTOR=CeleryExecutor
        depends_on:
            - webserver
        volumes:
          - ./dags:/airflow/dags
        command: sh -c "sleep 5 && airflow scheduler"

    worker:
        build: .
        image: henryturner27/airflow
        user: airflow
        restart: always
        environment:
            - EXECUTOR=CeleryExecutor
        depends_on:
            - scheduler
        expose:
            - 8793
        volumes:
          - ./dags:/airflow/dags
        command: sh -c "sleep 5 && airflow celery worker"

volumes:
    db_data:
